### ISSUE TITLE
QRCODE Implementation

### ISSUE THREAD

**Issue by netgg93** [lukevp/ESC-POS-.NET#18] opened 2019-08-15 04:02 UTC
Hey Guys

I have implemented Qr-code printing functionality. I'm a beginner in programming so I'm not sure how to submit the code here. Is there a way way I could submit my code here for you guys to review. 

Cheers!!

![QRCODE](https://user-images.githubusercontent.com/54124839/63072086-10c67b00-bf76-11e9-857e-3d421cfb1861.jpeg)

**Comment by netgg93** [comment] 2019-08-15 05:23
I have created pull request for review of the code.
Cheers!!

**Comment by lukevp** [comment] 2019-08-20 22:41
Hey @netgg93 , thank you for contributing! The code looks good, although I haven't reviewed it in depth.  The only issue with proceeding on the PRs is that your changes are in separate branches, so it's difficult to review and comment on them like this.  We're using GitFlow for this project, so it would be more appropriate for you to create a PR for merging your remote develop branch into the project's develop branch.

So next steps for you would be to close all 4 of your PRs, then merge your different branches into your develop branch, and then create a single PR for netgg93/develop to lukevp/develop that includes all your changes.  I'll then review and comment on it and once we resolve any issues it will get merged.

Thank you again for your work!

**Comment by lukevp** [comment] 2019-08-24 14:35
hey @netgg93 please see above. I'm closing this as a duplicate of #4 and I am closing the PRs, but if you follow the directions above and tie your PR to issue #4 we can review it there. Thanks again!

**Closed by lukevp** 2019-08-24 14:35 UTC
